# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alias',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='herostats',
            name='hero',
        ),
        migrations.DeleteModel(
            name='HeroStatus',
        ),
        migrations.DeleteModel(
            name='Alias',
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.DeleteModel(
            name='HeroStats',
        ),
    ]
