# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_auto_20160222_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='title',
            field=models.CharField(default='DEFAULT VALUE', max_length=30),
        ),
    ]
