# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('citizenship', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('intelligence', models.CharField(choices=[('1', 'Extremely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Average'), ('5', 'Good'), ('6', 'Above Average'), ('7', 'High'), ('8', 'Very High'), ('9', 'Super Human'), ('10', 'Above and Beyond')], max_length=5)),
                ('stamina', models.CharField(choices=[('1', 'Extremely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Average'), ('5', 'Good'), ('6', 'Above Average'), ('7', 'High'), ('8', 'Very High'), ('9', 'Super Human'), ('10', 'Above and Beyond')], max_length=5)),
                ('strength', models.CharField(choices=[('1', 'Extremely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Average'), ('5', 'Good'), ('6', 'Above Average'), ('7', 'High'), ('8', 'Very High'), ('9', 'Super Human'), ('10', 'Above and Beyond')], max_length=5)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.Hero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alias',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.Hero'),
        ),
    ]
