# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_ID', models.IntegerField()),
                ('hero_ID', models.IntegerField()),
                ('room_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_ID', models.IntegerField()),
                ('hero_ID', models.IntegerField()),
                ('outcome', models.CharField(choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1)),
                ('comments', models.TextField()),
                ('trainer', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reportlog',
            unique_together=set([('class_ID', 'hero_ID', 'trainer')]),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('class_ID', 'hero_ID')]),
        ),
    ]
