# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20160222_2135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
