# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_delete_hero'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='reportlog',
            unique_together=set([]),
        ),
    ]
